"""added account_code to relevant tables

Revision ID: 0216d3958685
Revises: 021e050885c3
Create Date: 2026-02-11 09:33:20.066427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0216d3958685'
down_revision: Union[str, None] = '021e050885c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_expenses', sa.Column('account_code', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'operational_expenses', 'chart_of_accounts', ['account_code'], ['account_code'])
    op.add_column('payments', sa.Column('account_code', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'payments', 'chart_of_accounts', ['account_code'], ['account_code'])
    op.add_column('sales_payments', sa.Column('account_code', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'sales_payments', 'chart_of_accounts', ['account_code'], ['account_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_payments', type_='foreignkey')
    op.drop_column('sales_payments', 'account_code')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'account_code')
    op.drop_constraint(None, 'operational_expenses', type_='foreignkey')
    op.drop_column('operational_expenses', 'account_code')
    # ### end Alembic commands ###
