"""Alter age column to numeric

Revision ID: 021e050885c3
Revises: 9e232d0b7163
Create Date: 2026-02-05 22:40:02.917591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021e050885c3'
down_revision: Union[str, None] = '9e232d0b7163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True,
               postgresql_using='age::numeric(4,1)')
    op.alter_column('daily_batch', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True,
               postgresql_using='age::numeric(4,1)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_batch', 'age',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='age::varchar')
    op.alter_column('batch', 'age',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='age::varchar')
    # ### end Alembic commands ###
