"""modify subscription table

Revision ID: 063a640cae7b
Revises: ef443c81c53b
Create Date: 2026-03-26 08:56:02.974947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '063a640cae7b'
down_revision: Union[str, None] = 'ef443c81c53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compositions_id', table_name='compositions')
    op.drop_index('ix_compositions_name', table_name='compositions')
    op.drop_table('compositions')
    
    # Drop foreign key constraint first
    op.drop_constraint('subscriptions_plan_id_fkey', 'subscriptions', type_='foreignkey')
    
    # Now drop the columns that reference subscription_plans
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'grace_period_end_date')
    
    # Now we can safely drop the subscription_plans table
    op.drop_index('ix_subscription_plans_id', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    
    # Add new columns
    op.add_column('subscriptions', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('subscriptions', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('notes', sa.String(), nullable=True))
    
    # Update tenant_id to be unique and not nullable
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('grace_period_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'GRACE_PERIOD', 'EXPIRED', name='subscriptionstatus'), autoincrement=False, nullable=False))
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscriptions', 'notes')
    op.drop_column('subscriptions', 'payment_date')
    op.drop_column('subscriptions', 'is_paid')
    op.create_table('subscription_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='subscriptionplanstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscription_plans_pkey'),
    sa.UniqueConstraint('name', name='subscription_plans_name_key')
    )
    op.create_index('ix_subscription_plans_id', 'subscription_plans', ['id'], unique=False)
    op.create_table('compositions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wastage_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='compositions_pkey')
    )
    op.create_index('ix_compositions_name', 'compositions', ['name'], unique=False)
    op.create_index('ix_compositions_id', 'compositions', ['id'], unique=False)
    # ### end Alembic commands ###
