"""added jumbo_out column and removed other columns

Revision ID: 10145adbab24
Revises: f5e7fb7f0b0a
Create Date: 2025-07-24 23:15:55.454443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10145adbab24'
down_revision: Union[str, None] = 'f5e7fb7f0b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_app_config_id', table_name='app_config')
    # op.drop_table('app_config')
    op.drop_constraint('batch_batch_no_key', 'batch', type_='unique')
    op.drop_constraint('batch_shed_no_key', 'batch', type_='unique')
    op.add_column('egg_room_reports', sa.Column('jumbo_out', sa.Integer(), nullable=True))
    op.drop_column('egg_room_reports', 'jumbo_in')
    op.drop_column('egg_room_reports', 'grade_c_room_received')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('grade_c_room_received', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_in', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('egg_room_reports', 'jumbo_out')
    op.create_unique_constraint('batch_shed_no_key', 'batch', ['shed_no'])
    op.create_unique_constraint('batch_batch_no_key', 'batch', ['batch_no'])
    # op.create_table('app_config',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='app_config_pkey'),
    # sa.UniqueConstraint('name', name='app_config_name_key')
    # )
    # op.create_index('ix_app_config_id', 'app_config', ['id'], unique=False)
    # ### end Alembic commands ###
