"""remove constraint in operational_expenses

Revision ID: 1c8f18d04116
Revises: 9a2c50ab9e26
Create Date: 2026-06-27 17:40:31.585304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8f18d04116'
down_revision: Union[str, None] = '9a2c50ab9e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_tenant_date_account_uc', 'operational_expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_tenant_date_account_uc', 'operational_expenses', ['tenant_id', 'expense_date', 'account_id'])
    # ### end Alembic commands ###
