"""alter quantity column datatype

Revision ID: 1e785df001c0
Revises: 3cc1c49081f8
Create Date: 2025-06-19 14:00:35.318122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e785df001c0'
down_revision: Union[str, None] = '3cc1c49081f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=8, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'quantity',
               existing_type=sa.Numeric(precision=8, scale=3),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
