"""reverting egg_room_report table removing sales related columns

Revision ID: 25d6a43aca93
Revises: 71c9832e8c5a
Create Date: 2025-09-20 08:00:04.220073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d6a43aca93'
down_revision: Union[str, None] = '71c9832e8c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egg_room_reports', 'table_sold')
    op.drop_column('egg_room_reports', 'grade_c_sold')
    op.drop_column('egg_room_reports', 'jumbo_sold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('jumbo_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('grade_c_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('table_sold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
