"""Update SalesOrder relationships

Revision ID: 26b04b334a67
Revises: e1dff6f90ae6
Create Date: 2025-08-16 09:00:37.066910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b04b334a67'
down_revision: Union[str, None] = 'e1dff6f90ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint('sales_orders_vendor_id_fkey', 'sales_orders', type_='foreignkey')
    op.create_foreign_key(None, 'sales_orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('sales_orders', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_vendor_id_fkey', 'sales_orders', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('sales_orders', 'customer_id')
    # ### end Alembic commands ###
