"""add untrayed_eggs to egg_room_reports

Revision ID: 2786d1eea53a
Revises: f5c6f13abcb3
Create Date: 2026-06-01 20:36:49.586031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2786d1eea53a'
down_revision: Union[str, None] = 'f5c6f13abcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('table_untrayed', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('grade_c_untrayed', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_untrayed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egg_room_reports', 'jumbo_untrayed')
    op.drop_column('egg_room_reports', 'grade_c_untrayed')
    op.drop_column('egg_room_reports', 'table_untrayed')
    # ### end Alembic commands ###
