"""date column to expense date in operational_expenses

Revision ID: 2a9f9b1ecac8
Revises: 99e32f7690ed
Create Date: 2026-02-17 08:00:26.745683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a9f9b1ecac8'
down_revision: Union[str, None] = '99e32f7690ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operational_expenses', 'date', new_column_name='expense_date')
    op.add_column('operational_expenses', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('_tenant_date_expense_uc', 'operational_expenses', type_='unique')
    op.create_unique_constraint('_tenant_date_expense_uc', 'operational_expenses', ['tenant_id', 'expense_date', 'expense_type'])
    op.drop_constraint('operational_expenses_tenant_account_fkey', 'operational_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'operational_expenses', 'chart_of_accounts', ['account_id'], ['id'])
    op.drop_column('operational_expenses', 'account_code')
    # op.drop_column('operational_expenses', 'date')
    op.add_column('payments', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('payments_tenant_account_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'chart_of_accounts', ['account_id'], ['id'])
    op.drop_column('payments', 'account_code')
    op.add_column('sales_payments', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_constraint('sales_payments_tenant_account_fkey', 'sales_payments', type_='foreignkey')
    op.create_foreign_key(None, 'sales_payments', 'chart_of_accounts', ['account_id'], ['id'])
    op.drop_column('sales_payments', 'account_code')
    op.drop_constraint('_tenant_date_expense_uc', 'operational_expenses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_payments', sa.Column('account_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_payments', type_='foreignkey')
    op.create_foreign_key('sales_payments_tenant_account_fkey', 'sales_payments', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])
    op.drop_column('sales_payments', 'account_id')
    op.add_column('payments', sa.Column('account_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_tenant_account_fkey', 'payments', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])
    op.drop_column('payments', 'account_id')
    op.add_column('operational_expenses', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('operational_expenses', sa.Column('account_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operational_expenses', type_='foreignkey')
    op.create_foreign_key('operational_expenses_tenant_account_fkey', 'operational_expenses', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])
    op.drop_column('operational_expenses', 'account_id')
    op.drop_column('operational_expenses', 'expense_date')
    # ### end Alembic commands ###
