"""added total amount column in purchase model

Revision ID: 2dec74d9c307
Revises: 63b010c205f5
Create Date: 2025-08-14 07:47:54.257156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dec74d9c307'
down_revision: Union[str, None] = '63b010c205f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_receipt', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'payment_receipt')
    # ### end Alembic commands ###
