"""added bill_no column in purchase and sales orders

Revision ID: 3a8b68709bed
Revises: a1fdb0f8f2ba
Create Date: 2025-12-16 11:21:21.434948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8b68709bed'
down_revision: Union[str, None] = 'a1fdb0f8f2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('bill_no', sa.String(), nullable=True))
    op.add_column('sales_orders', sa.Column('bill_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'bill_no')
    op.drop_column('purchase_orders', 'bill_no')
    # ### end Alembic commands ###
