"""Remove table_transfer column from egg_room_reports

Revision ID: 3c4a42355c4d
Revises: 07ea1eaed8d6
Create Date: 2026-01-03 13:22:43.048241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4a42355c4d'
down_revision: Union[str, None] = '07ea1eaed8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egg_room_reports', 'table_transfer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('table_transfer', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
