"""add feed wastage related columns

Revision ID: 41cbd2679317
Revises: 63173a2edb1f
Create Date: 2025-12-20 08:10:25.523587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cbd2679317'
down_revision: Union[str, None] = '63173a2edb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composition_usage_item', sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('inventory_item_in_composition', sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('inventory_items', sa.Column('default_wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'default_wastage_percentage')
    op.drop_column('inventory_item_in_composition', 'wastage_percentage')
    op.drop_column('composition_usage_item', 'wastage_percentage')
    # ### end Alembic commands ###
