"""add_feed_variance_weight

Revision ID: 436610aec827
Revises: aecb611b4c46
Create Date: 2026-06-26 10:26:16.632870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436610aec827'
down_revision: Union[str, None] = 'aecb611b4c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composition_usage_history', sa.Column('feed_variance_weight', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composition_usage_history', 'feed_variance_weight')
    # ### end Alembic commands ###
