"""update feed table

Revision ID: 46b45060f87a
Revises: 82eddb9e2def
Create Date: 2025-05-15 22:13:34.173983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b45060f87a'
down_revision: Union[str, None] = '82eddb9e2def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('createdDate', sa.Date(), nullable=True))
    op.drop_column('feed', 'last_used_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('last_used_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('feed', 'createdDate')
    # ### end Alembic commands ###
