"""added tenant id

Revision ID: 5114344c0856
Revises: dd3a93acd767
Create Date: 2025-09-12 19:02:52.675933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5114344c0856'
down_revision: Union[str, None] = 'dd3a93acd767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_batch_tenant_id'), 'batch', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_tenant_id'), table_name='batch')
    op.drop_column('batch', 'tenant_id')
    # ### end Alembic commands ###
