"""renamed uploaded_date to upload_date

Revision ID: 57b974ff7a08
Revises: 36f7488cd139
Create Date: 2025-06-05 09:02:37.175254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b974ff7a08'
down_revision: Union[str, None] = '36f7488cd139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('upload_date', sa.Date(), nullable=True))
    op.drop_column('daily_batch', 'uploaded_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('uploaded_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('daily_batch', 'upload_date')
    # ### end Alembic commands ###
