"""added tenant id

Revision ID: 5b94234f5995
Revises: 97d72cc32ca6
Create Date: 2025-09-17 07:03:52.820702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b94234f5995'
down_revision: Union[str, None] = '97d72cc32ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_egg_room_reports_tenant_id'), 'egg_room_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_egg_room_reports_tenant_id'), table_name='egg_room_reports')
    op.drop_column('egg_room_reports', 'tenant_id')
    # ### end Alembic commands ###
