"""Added HD column

Revision ID: 5c2994a762bd
Revises: 46b45060f87a
Create Date: 2025-05-29 19:09:43.394769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2994a762bd'
down_revision: Union[str, None] = '46b45060f87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('HD', sa.Integer(), nullable=True))
    op.add_column('daily_batch', sa.Column('HD', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_batch', 'HD')
    op.drop_column('batch', 'HD')
    # ### end Alembic commands ###
