"""Add audit trail to inventory and batch models

Revision ID: 5e4138b12517
Revises: 70961fc98c88
Create Date: 2025-10-09 23:48:44.896907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4138b12517'
down_revision: Union[str, None] = '70961fc98c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('batch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('batch', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('batch', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('daily_batch', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('daily_batch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('daily_batch', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('daily_batch', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('inventory_items', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'updated_by')
    op.drop_column('inventory_items', 'created_by')
    op.drop_column('daily_batch', 'updated_by')
    op.drop_column('daily_batch', 'created_by')
    op.drop_column('daily_batch', 'updated_at')
    op.drop_column('daily_batch', 'created_at')
    op.drop_column('batch', 'updated_by')
    op.drop_column('batch', 'created_by')
    op.drop_column('batch', 'updated_at')
    op.drop_column('batch', 'created_at')
    # ### end Alembic commands ###
