"""added total amount column in purchase model

Revision ID: 63b010c205f5
Revises: feb67b746cd4
Create Date: 2025-08-13 23:15:12.940114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b010c205f5'
down_revision: Union[str, None] = 'feb67b746cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('total_amount_paid', sa.Numeric(precision=10, scale=3), nullable=False, server_default='0.0'))
    op.drop_constraint('purchase_orders_po_number_key', 'purchase_orders', type_='unique')
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'po_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('po_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_unique_constraint('purchase_orders_po_number_key', 'purchase_orders', ['po_number'])
    op.drop_column('purchase_orders', 'total_amount_paid')
    # ### end Alembic commands ###
