"""changes for feed wastage

Revision ID: 6598c883dc3e
Revises: a2df71dc5bb0
Create Date: 2025-07-18 21:43:40.301638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6598c883dc3e'
down_revision: Union[str, None] = 'a2df71dc5bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_app_config_id', table_name='app_config')
    # op.drop_table('app_config')
    op.add_column('composition_usage_history', sa.Column('weight_of_composition', sa.Float(), nullable=False))
    op.add_column('composition_usage_history', sa.Column('wastage', sa.Float(), nullable=True))
    op.alter_column('composition_usage_history', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'composition_usage_history', 'batch', ['batch_id'], ['id'])
    op.drop_column('composition_usage_history', 'times')
    op.add_column('feed_in_composition', sa.Column('wastage_in_percentage', sa.Float(), nullable=True))
    op.add_column('feed_in_composition', sa.Column('wastage_in_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_in_composition', 'wastage_in_kg')
    op.drop_column('feed_in_composition', 'wastage_in_percentage')
    op.add_column('composition_usage_history', sa.Column('times', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'composition_usage_history', type_='foreignkey')
    op.alter_column('composition_usage_history', 'batch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('composition_usage_history', 'wastage')
    op.drop_column('composition_usage_history', 'weight_of_composition')
    # op.create_table('app_config',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='app_config_pkey'),
    # sa.UniqueConstraint('name', name='app_config_name_key')
    # )
    # op.create_index('ix_app_config_id', 'app_config', ['id'], unique=False)
    # ### end Alembic commands ###
