"""Add sold columns to egg room reports

Revision ID: 6a3a38d829fa
Revises: 5b94234f5995
Create Date: 2025-09-18 21:53:35.958858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a38d829fa'
down_revision: Union[str, None] = '5b94234f5995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('table_sold', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_sold', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('grade_c_sold', sa.Integer(), nullable=True))
    op.alter_column('egg_room_reports', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_egg_room_reports_tenant_id'), 'egg_room_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_egg_room_reports_tenant_id'), table_name='egg_room_reports')
    op.alter_column('egg_room_reports', 'tenant_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('egg_room_reports', 'grade_c_sold')
    op.drop_column('egg_room_reports', 'jumbo_sold')
    op.drop_column('egg_room_reports', 'table_sold')
    # ### end Alembic commands ###
