"""reverting egg_room_report table removing sales related columns

Revision ID: 71c9832e8c5a
Revises: 6a3a38d829fa
Create Date: 2025-09-20 07:29:13.874963

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '71c9832e8c5a'
down_revision: Union[str, None] = '6a3a38d829fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
