"""financial settings alter

Revision ID: 7254b9e6d9da
Revises: 2a9f9b1ecac8
Create Date: 2026-02-18 23:03:00.675850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7254b9e6d9da'
down_revision: Union[str, None] = '2a9f9b1ecac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_settings', sa.Column('default_accounts_payable_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'financial_settings', 'chart_of_accounts', ['default_accounts_payable_account_id'], ['id'])
    op.alter_column('operational_expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_unique_constraint('_tenant_date_expense_uc', 'operational_expenses', ['tenant_id', 'expense_date', 'expense_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_tenant_date_expense_uc', 'operational_expenses', type_='unique')
    op.alter_column('operational_expenses', 'expense_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'financial_settings', type_='foreignkey')
    op.drop_column('financial_settings', 'default_accounts_payable_account_id')
    # ### end Alembic commands ###
