"""Add BatchShedAssignment table and remove shed_id from batch

Revision ID: 72a367040db1
Revises: 92d87af5d660
Create Date: 2025-11-13 22:10:50.652700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a367040db1'
down_revision: Union[str, None] = '92d87af5d660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('batch_shed_id_fkey', 'batch', type_='foreignkey')
    op.drop_column('batch', 'shed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('shed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('batch_shed_id_fkey', 'batch', 'sheds', ['shed_id'], ['id'])
    # ### end Alembic commands ###
