"""Add birds_added column to daily_batch table

Revision ID: 731b8353272e
Revises: 07ea1eaed8d6
Create Date: 2026-01-20 07:44:25.433497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731b8353272e'
down_revision: Union[str, None] = '07ea1eaed8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('birds_added', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_batch', 'birds_added')
    # ### end Alembic commands ###
