"""added tenant_id  to relevant tables

Revision ID: 7dbcc522912d
Revises: fix_chart_of_accounts_constraint
Create Date: 2026-02-14 12:10:19.176846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbcc522912d'
down_revision: Union[str, None] = 'fix_chart_of_accounts_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraints that depend on the index
    op.drop_constraint('operational_expenses_account_code_fkey', 'operational_expenses', type_='foreignkey')
    op.drop_constraint('payments_account_code_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('sales_payments_account_code_fkey', 'sales_payments', type_='foreignkey')

    # Drop the index
    op.drop_index('ix_chart_of_accounts_account_code', table_name='chart_of_accounts')

    # Create a non-unique index for account_code
    op.create_index(op.f('ix_chart_of_accounts_account_code'), 'chart_of_accounts', ['account_code'], unique=False)

    # Add tenant_id to operational_expenses, payments, and sales_payments if not already there
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Add tenant_id to operational_expenses if not exists
    if 'tenant_id' not in [c['name'] for c in inspector.get_columns('operational_expenses')]:
        op.add_column('operational_expenses', sa.Column('tenant_id', sa.String(), nullable=False))

    # Add tenant_id to payments if not exists
    if 'tenant_id' not in [c['name'] for c in inspector.get_columns('payments')]:
        op.add_column('payments', sa.Column('tenant_id', sa.String(), nullable=False))

    # Add tenant_id to sales_payments if not exists
    if 'tenant_id' not in [c['name'] for c in inspector.get_columns('sales_payments')]:
        op.add_column('sales_payments', sa.Column('tenant_id', sa.String(), nullable=False))

    # Add tenant_id to journal_items
    op.add_column('journal_items', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_journal_items_tenant_id'), 'journal_items', ['tenant_id'], unique=False)

    # Create composite unique constraint on chart_of_accounts for tenant_id and account_code if it doesn't exist
    constraints = inspector.get_unique_constraints('chart_of_accounts')
    constraint_exists = any(c['name'] == '_tenant_account_code_uc' for c in constraints)

    if not constraint_exists:
        op.create_unique_constraint('_tenant_account_code_uc', 'chart_of_accounts', ['tenant_id', 'account_code'])

    # Create composite foreign key constraints if they don't exist
    fk_constraints = inspector.get_foreign_keys('operational_expenses')
    if not any(c['name'] == 'operational_expenses_tenant_account_fkey' for c in fk_constraints):
        op.create_foreign_key('operational_expenses_tenant_account_fkey', 'operational_expenses', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])

    fk_constraints = inspector.get_foreign_keys('payments')
    if not any(c['name'] == 'payments_tenant_account_fkey' for c in fk_constraints):
        op.create_foreign_key('payments_tenant_account_fkey', 'payments', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])

    fk_constraints = inspector.get_foreign_keys('sales_payments')
    if not any(c['name'] == 'sales_payments_tenant_account_fkey' for c in fk_constraints):
        op.create_foreign_key('sales_payments_tenant_account_fkey', 'sales_payments', 'chart_of_accounts', ['tenant_id', 'account_code'], ['tenant_id', 'account_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Get connection and inspector
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Drop composite foreign key constraints if they exist
    fk_constraints = inspector.get_foreign_keys('operational_expenses')
    if any(c['name'] == 'operational_expenses_tenant_account_fkey' for c in fk_constraints):
        op.drop_constraint('operational_expenses_tenant_account_fkey', 'operational_expenses', type_='foreignkey')

    fk_constraints = inspector.get_foreign_keys('payments')
    if any(c['name'] == 'payments_tenant_account_fkey' for c in fk_constraints):
        op.drop_constraint('payments_tenant_account_fkey', 'payments', type_='foreignkey')

    fk_constraints = inspector.get_foreign_keys('sales_payments')
    if any(c['name'] == 'sales_payments_tenant_account_fkey' for c in fk_constraints):
        op.drop_constraint('sales_payments_tenant_account_fkey', 'sales_payments', type_='foreignkey')

    # Drop composite unique constraint if it exists
    constraints = inspector.get_unique_constraints('chart_of_accounts')
    if any(c['name'] == '_tenant_account_code_uc' for c in constraints):
        op.drop_constraint('_tenant_account_code_uc', 'chart_of_accounts', type_='unique')

    # Drop tenant_id from journal_items
    op.drop_index(op.f('ix_journal_items_tenant_id'), table_name='journal_items')
    op.drop_column('journal_items', 'tenant_id')

    # Drop tenant_id from operational_expenses, payments, and sales_payments
    op.drop_column('operational_expenses', 'tenant_id')
    op.drop_column('payments', 'tenant_id')
    op.drop_column('sales_payments', 'tenant_id')

    # Drop the current index
    op.drop_index(op.f('ix_chart_of_accounts_account_code'), table_name='chart_of_accounts')

    # Recreate the index as unique
    op.create_index('ix_chart_of_accounts_account_code', 'chart_of_accounts', ['account_code'], unique=True)

    # Create simple foreign key constraints
    op.create_foreign_key('operational_expenses_account_code_fkey', 'operational_expenses', 'chart_of_accounts', ['account_code'], ['account_code'])
    op.create_foreign_key('payments_account_code_fkey', 'payments', 'chart_of_accounts', ['account_code'], ['account_code'])
    op.create_foreign_key('sales_payments_account_code_fkey', 'sales_payments', 'chart_of_accounts', ['account_code'], ['account_code'])
    # ### end Alembic commands ###
