"""daily_batch_batch_no_reomove_constraint

Revision ID: 82eddb9e2def
Revises: 9cb16e3be013
Create Date: 2025-04-25 15:58:18.898792

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '82eddb9e2def'
down_revision: Union[str, None] = '9cb16e3be013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daily_batch_batch_no_key', 'daily_batch', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('daily_batch_batch_no_key', 'daily_batch', ['batch_no'])
    # ### end Alembic commands ###
