"""financial settings alter

Revision ID: 8cb0cb15c842
Revises: 7254b9e6d9da
Create Date: 2026-02-19 07:06:30.307337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb0cb15c842'
down_revision: Union[str, None] = '7254b9e6d9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_settings', sa.Column('default_accounts_receivable_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'financial_settings', 'chart_of_accounts', ['default_accounts_receivable_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_settings', type_='foreignkey')
    op.drop_column('financial_settings', 'default_accounts_receivable_account_id')
    # ### end Alembic commands ###
