"""Update SalesOrder relationships

Revision ID: 8fc435cd5d62
Revises: 5e653fe488bd
Create Date: 2025-08-16 08:51:43.084737

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '8fc435cd5d62'
down_revision: Union[str, None] = '5e653fe488bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass