"""Add variant tracking to sales order items

Revision ID: 928ea9971379
Revises: 41cbd2679317
Create Date: 2025-12-26 17:19:46.365954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928ea9971379'
down_revision: Union[str, None] = '41cbd2679317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_items', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('sales_order_items', sa.Column('variant_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sales_order_items', 'inventory_item_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.drop_column('sales_order_items', 'variant_name')
    op.drop_column('sales_order_items', 'variant_id')
    # ### end Alembic commands ###
