"""add_shed_id_to_batch_and_daily_batch

Revision ID: 92d87af5d660
Revises: 357139345a4a
Create Date: 2025-11-12 13:30:00.121207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d87af5d660'
down_revision: Union[str, None] = 'c37a2bed5471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('shed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batch', 'sheds', ['shed_id'], ['id'])
    op.add_column('daily_batch', sa.Column('shed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_batch', 'sheds', ['shed_id'], ['id'])

    # Populate the new shed_id columns
    op.execute("""
        UPDATE batch
        SET shed_id = sheds.id
        FROM sheds
        WHERE batch.shed_no = sheds.shed_no AND batch.tenant_id = sheds.tenant_id
    """)
    op.execute("""
        UPDATE daily_batch
        SET shed_id = sheds.id
        FROM sheds
        WHERE daily_batch.shed_no = sheds.shed_no AND daily_batch.tenant_id = sheds.tenant_id
    """)

    op.drop_column('batch', 'shed_no')
    op.drop_column('daily_batch', 'shed_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('shed_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'daily_batch', type_='foreignkey')
    op.drop_column('daily_batch', 'shed_id')
    op.add_column('batch', sa.Column('shed_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'shed_id')
    # ### end Alembic commands ###