"""add_shed_id_to_batch_and_daily_batch

Revision ID: 92d87af5d660
Revises: 357139345a4a
Create Date: 2025-11-12 13:30:00.121207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d87af5d660'
down_revision: Union[str, None] = 'c37a2bed5471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:


    # ### commands auto generated by Alembic - please adjust! ###





    # Step 1: Find all unique sheds from batch and daily_batch tables


    # and insert them into the 'sheds' table. This ensures that the


    # sheds table is populated before we try to use it for mapping.


    op.execute("""


        INSERT INTO sheds (shed_no, tenant_id, created_at, updated_at)


        SELECT DISTINCT shed_no, tenant_id, NOW(), NOW()


        FROM (


            SELECT shed_no, tenant_id FROM batch WHERE shed_no IS NOT NULL


            UNION


            SELECT shed_no, tenant_id FROM daily_batch WHERE shed_no IS NOT NULL


        ) as existing_sheds


        WHERE existing_sheds.shed_no IS NOT NULL AND existing_sheds.tenant_id IS NOT NULL


        ON CONFLICT (shed_no, tenant_id) DO NOTHING;


    """)





    # Step 2: Add the new shed_id column to the daily_batch table ONLY.


    op.add_column('daily_batch', sa.Column('shed_id', sa.Integer(), nullable=True))


    op.create_foreign_key('fk_daily_batch_shed_id', 'daily_batch', 'sheds', ['shed_id'], ['id'])





    # Step 3: Populate the new shed_id column by matching the old shed_no.


    op.execute("""


        UPDATE daily_batch


        SET shed_id = sheds.id


        FROM sheds


        WHERE daily_batch.shed_no = sheds.shed_no AND daily_batch.tenant_id = sheds.tenant_id


    """)





    # Step 3.5: Create initial shed assignments for all existing batches.


    # This is crucial for the application logic (move, swap, close) to work for old batches.


    op.execute("""


        INSERT INTO batch_shed_assignments (batch_id, shed_id, start_date, end_date, created_by, updated_by, created_at, updated_at)


        SELECT


            b.id,


            s.id,


            b.date,


            b.closing_date, -- This will be NULL for active batches, correctly leaving the assignment open.


            COALESCE(b.created_by, 'migration'),


            COALESCE(b.updated_by, 'migration'),


            COALESCE(b.created_at, NOW()),


            COALESCE(b.updated_at, NOW())


        FROM


            batch AS b


        JOIN


            sheds AS s ON b.shed_no = s.shed_no AND b.tenant_id = s.tenant_id


        ON CONFLICT (batch_id, shed_id, start_date) DO NOTHING;


    """)





    # Step 4: Drop the old shed_no columns from both tables as they are now redundant.


    op.drop_column('batch', 'shed_no')


    op.drop_column('daily_batch', 'shed_no')


    # ### end Alembic commands ###








def downgrade() -> None:


    # ### commands auto generated by Alembic - please adjust! ###





    # Step 1: Re-add the 'shed_no' columns, making them nullable for now.


    op.add_column('daily_batch', sa.Column('shed_no', sa.String(), nullable=True))


    op.add_column('batch', sa.Column('shed_no', sa.String(), nullable=True))





    # Step 2: Populate the restored 'shed_no' columns.


    # First, restore for daily_batch using the shed_id.


    op.execute("""


        UPDATE daily_batch


        SET shed_no = sheds.shed_no


        FROM sheds


        WHERE daily_batch.shed_id = sheds.id


    """)


    # Second, restore for batch by looking up the value from the just-restored daily_batch table.


    # This is a best-effort restoration based on the batch's start date.


    op.execute("""


        UPDATE batch


        SET shed_no = daily_batch.shed_no


        FROM daily_batch


        WHERE batch.id = daily_batch.batch_id AND batch.date = daily_batch.batch_date


    """)





    # Step 3: Drop the 'shed_id' column and its foreign key constraint from daily_batch.


    op.drop_constraint('fk_daily_batch_shed_id', 'daily_batch', type_='foreignkey')


    op.drop_column('daily_batch', 'shed_id')





    # Step 4: Remove the initial shed assignments created in the upgrade.


    op.execute("""


        DELETE FROM batch_shed_assignments


        WHERE batch_id IN (SELECT id FROM batch);


    """)


    # ### end Alembic commands ###

