"""added tenent id

Revision ID: 97d72cc32ca6
Revises: c09dfb94579d
Create Date: 2025-09-16 08:07:21.502760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d72cc32ca6'
down_revision: Union[str, None] = 'c09dfb94579d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.add_column('app_config', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_app_config_tenant_id'), 'app_config', ['tenant_id'], unique=False)
    op.add_column('bovanswhitelayerperformance', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_bovanswhitelayerperformance_tenant_id'), 'bovanswhitelayerperformance', ['tenant_id'], unique=False)
    op.add_column('composition', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_composition_tenant_id'), 'composition', ['tenant_id'], unique=False)
    op.add_column('composition_usage_history', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_composition_usage_history_tenant_id'), 'composition_usage_history', ['tenant_id'], unique=False)
    op.add_column('inventory_item_audit', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_inventory_item_audit_tenant_id'), 'inventory_item_audit', ['tenant_id'], unique=False)
    op.add_column('inventory_item_in_composition', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_inventory_item_in_composition_tenant_id'), 'inventory_item_in_composition', ['tenant_id'], unique=False)
    op.add_column('inventory_item_usage_history', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_inventory_item_usage_history_tenant_id'), 'inventory_item_usage_history', ['tenant_id'], unique=False)
    op.add_column('payments', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.add_column('purchase_order_items', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchase_order_items_tenant_id'), 'purchase_order_items', ['tenant_id'], unique=False)
    op.add_column('purchase_orders', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.add_column('sales_order_items', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_order_items_tenant_id'), 'sales_order_items', ['tenant_id'], unique=False)
    op.add_column('sales_orders', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_orders_tenant_id'), 'sales_orders', ['tenant_id'], unique=False)
    op.add_column('sales_payments', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_payments_tenant_id'), 'sales_payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_payments_tenant_id'), table_name='sales_payments')
    op.drop_column('sales_payments', 'tenant_id')
    op.drop_index(op.f('ix_sales_orders_tenant_id'), table_name='sales_orders')
    op.drop_column('sales_orders', 'tenant_id')
    op.drop_index(op.f('ix_sales_order_items_tenant_id'), table_name='sales_order_items')
    op.drop_column('sales_order_items', 'tenant_id')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'tenant_id')
    op.drop_index(op.f('ix_purchase_order_items_tenant_id'), table_name='purchase_order_items')
    op.drop_column('purchase_order_items', 'tenant_id')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_column('payments', 'tenant_id')
    op.drop_index(op.f('ix_inventory_item_usage_history_tenant_id'), table_name='inventory_item_usage_history')
    op.drop_column('inventory_item_usage_history', 'tenant_id')
    op.drop_index(op.f('ix_inventory_item_in_composition_tenant_id'), table_name='inventory_item_in_composition')
    op.drop_column('inventory_item_in_composition', 'tenant_id')
    op.drop_index(op.f('ix_inventory_item_audit_tenant_id'), table_name='inventory_item_audit')
    op.drop_column('inventory_item_audit', 'tenant_id')
    op.drop_index(op.f('ix_composition_usage_history_tenant_id'), table_name='composition_usage_history')
    op.drop_column('composition_usage_history', 'tenant_id')
    op.drop_index(op.f('ix_composition_tenant_id'), table_name='composition')
    op.drop_column('composition', 'tenant_id')
    op.drop_index(op.f('ix_bovanswhitelayerperformance_tenant_id'), table_name='bovanswhitelayerperformance')
    op.drop_column('bovanswhitelayerperformance', 'tenant_id')
    op.drop_index(op.f('ix_app_config_tenant_id'), table_name='app_config')
    op.drop_column('app_config', 'tenant_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
