"""remove parent_account_code

Revision ID: 99e32f7690ed
Revises: 7dbcc522912d
Create Date: 2026-02-16 19:02:09.238860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e32f7690ed'
down_revision: Union[str, None] = '7dbcc522912d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_of_accounts', 'parent_account_code')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_of_accounts', sa.Column('parent_account_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
