"""changed data type from float to decimal for required fields

Revision ID: 9e232d0b7163
Revises: 731b8353272e
Create Date: 2026-02-05 00:11:41.192884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e232d0b7163'
down_revision: Union[str, None] = '731b8353272e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('composition_usage_item', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'change_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'old_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'new_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_item_in_composition', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_item_in_composition', 'weight',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'new_quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'old_quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('inventory_item_audit', 'change_amount',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('composition_usage_item', 'weight',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
