"""removed hybrid property columns

Revision ID: a2df71dc5bb0
Revises: 0e10c3d772fa
Create Date: 2025-07-18 07:29:04.351713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2df71dc5bb0'
down_revision: Union[str, None] = '0e10c3d772fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_app_config_id', table_name='app_config')
    # op.drop_table('app_config')
    op.create_index(op.f('ix_bovanswhitelayerperformance_age_weeks'), 'bovanswhitelayerperformance', ['age_weeks'], unique=False)
    # op.add_column('composition_usage_history', sa.Column('wastage', sa.Integer(), nullable=False))
    # op.alter_column('composition_usage_history', 'batch_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.create_foreign_key(None, 'composition_usage_history', 'batch', ['batch_id'], ['id'])
    op.drop_column('egg_room_reports', 'table_opening')
    op.drop_column('egg_room_reports', 'table_closing')
    op.drop_column('egg_room_reports', 'jumbo_opening')
    op.drop_column('egg_room_reports', 'grade_c_closing')
    op.drop_column('egg_room_reports', 'jumbo_closing')
    op.drop_column('egg_room_reports', 'grade_c_opening')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('grade_c_opening', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_closing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('grade_c_closing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_opening', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('table_closing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('egg_room_reports', sa.Column('table_opening', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'composition_usage_history', type_='foreignkey')
    # op.alter_column('composition_usage_history', 'batch_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.drop_column('composition_usage_history', 'wastage')
    op.drop_index(op.f('ix_bovanswhitelayerperformance_age_weeks'), table_name='bovanswhitelayerperformance')
    # op.create_table('app_config',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='app_config_pkey'),
    # sa.UniqueConstraint('name', name='app_config_name_key')
    # )
    # op.create_index('ix_app_config_id', 'app_config', ['id'], unique=False)
    # ### end Alembic commands ###
