"""added receipt to payments page

Revision ID: aff0ba81c53b
Revises: 2dec74d9c307
Create Date: 2025-08-14 20:55:32.813571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff0ba81c53b'
down_revision: Union[str, None] = '2dec74d9c307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_receipt', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_receipt')
    # ### end Alembic commands ###
