"""Update foreign key to support common vendor and customer

Revision ID: b0efad2bab4b
Revises: 26b04b334a67
Create Date: 2025-08-19 00:33:33.709844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0efad2bab4b'
down_revision: Union[str, None] = '26b04b334a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('purchase_orders_vendor_id_fkey', 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'business_partners', ['vendor_id'], ['id'])
    op.drop_constraint('sales_orders_customer_id_fkey', 'sales_orders', type_='foreignkey')
    op.create_foreign_key(None, 'sales_orders', 'business_partners', ['customer_id'], ['id'])
    op.drop_table('vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_foreign_key('sales_orders_customer_id_fkey', 'sales_orders', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key('purchase_orders_vendor_id_fkey', 'purchase_orders', 'vendors', ['vendor_id'], ['id'])
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'ON_HOLD', name='vendorstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vendors_pkey'),
    sa.UniqueConstraint('email', name='vendors_email_key'),
    sa.UniqueConstraint('name', name='vendors_name_key')
    )
    op.create_index('ix_vendors_id', 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###
