"""tenant specific id for purchase and sales orders

Revision ID: b76ead9195e8
Revises: f2b915cf5d7e
Create Date: 2025-09-28 23:23:07.545076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b76ead9195e8'
down_revision: Union[str, None] = 'f2b915cf5d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('composition_usage_history', 'composition_items',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.JSON(),
    #            existing_nullable=False)
    op.add_column('purchase_orders', sa.Column('po_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('_tenant_po_number_uc', 'purchase_orders', ['tenant_id', 'po_number'])
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.add_column('sales_orders', sa.Column('so_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('_tenant_so_number_uc', 'sales_orders', ['tenant_id', 'so_number'])
    op.create_index(op.f('ix_sales_orders_so_number'), 'sales_orders', ['so_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_orders_so_number'), table_name='sales_orders')
    op.drop_constraint('_tenant_so_number_uc', 'sales_orders', type_='unique')
    op.drop_column('sales_orders', 'so_number')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_constraint('_tenant_po_number_uc', 'purchase_orders', type_='unique')
    op.drop_column('purchase_orders', 'po_number')
    # op.alter_column('composition_usage_history', 'composition_items',
    #            existing_type=sa.JSON(),
    #            type_=postgresql.JSONB(astext_type=sa.Text()),
    #            existing_nullable=False)
    # ### end Alembic commands ###
