"""added tenent id

Revision ID: c09dfb94579d
Revises: 5114344c0856
Create Date: 2025-09-13 08:04:56.821832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09dfb94579d'
down_revision: Union[str, None] = '5114344c0856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_partners', sa.Column('tenant_id', sa.String(), nullable=True))
    op.drop_constraint('business_partners_email_key', 'business_partners', type_='unique')
    op.drop_constraint('business_partners_name_key', 'business_partners', type_='unique')
    op.create_index(op.f('ix_business_partners_tenant_id'), 'business_partners', ['tenant_id'], unique=False)
    op.add_column('daily_batch', sa.Column('tenant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_daily_batch_tenant_id'), 'daily_batch', ['tenant_id'], unique=False)
    op.add_column('inventory_items', sa.Column('tenant_id', sa.String(), nullable=True))
    op.drop_constraint('inventory_items_name_key', 'inventory_items', type_='unique')
    op.create_index(op.f('ix_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_tenant_id'), table_name='inventory_items')
    op.create_unique_constraint('inventory_items_name_key', 'inventory_items', ['name'])
    op.drop_column('inventory_items', 'tenant_id')
    op.drop_index(op.f('ix_daily_batch_tenant_id'), table_name='daily_batch')
    op.drop_column('daily_batch', 'tenant_id')
    op.drop_index(op.f('ix_business_partners_tenant_id'), table_name='business_partners')
    op.create_unique_constraint('business_partners_name_key', 'business_partners', ['name'])
    op.create_unique_constraint('business_partners_email_key', 'business_partners', ['email'])
    op.drop_column('business_partners', 'tenant_id')
    # ### end Alembic commands ###
