"""batch model change

Revision ID: c337bff8aeba
Revises: b5a23e5acac6
Create Date: 2025-06-21 14:57:38.532424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c337bff8aeba'
down_revision: Union[str, None] = 'b5a23e5acac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.drop_table('users')
    # op.drop_index('ix_app_config_id', table_name='app_config')
    # op.drop_table('app_config')
    op.drop_column('batch', 'hd')
    op.drop_column('batch', 'culls')
    op.drop_column('batch', 'mortality')
    op.drop_column('batch', 'cr')
    op.drop_column('batch', 'closing_count')
    op.drop_column('batch', 'table_eggs')
    op.drop_column('batch', 'jumbo')
    op.drop_column('daily_batch', 'closing_count')
    op.drop_column('daily_batch', 'hd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('hd', sa.NUMERIC(precision=11, scale=9), autoincrement=False, nullable=True))
    op.add_column('daily_batch', sa.Column('closing_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('jumbo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('table_eggs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('closing_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('cr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('mortality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('culls', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('batch', sa.Column('hd', sa.NUMERIC(precision=11, scale=9), autoincrement=False, nullable=True))
    # op.create_table('app_config',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='app_config_pkey'),
    # sa.UniqueConstraint('name', name='app_config_name_key')
    # )
    # op.create_index('ix_app_config_id', 'app_config', ['id'], unique=False)
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('is_superuser', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='users_pkey')
    # )
    # op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # # ### end Alembic commands ###
