"""Add tenant_id to DailyBatch primary key

Revision ID: c37a2bed5471
Revises: 40857073357f
Create Date: 2025-11-06 15:09:59.728645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c37a2bed5471'
down_revision: Union[str, None] = '40857073357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composition_usage_history', 'composition_items')
    op.alter_column('daily_batch', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_batch', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('composition_usage_history', sa.Column('composition_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
