"""change datatype of quantity in feed table

Revision ID: c54743fe68d3
Revises: 57b974ff7a08
Create Date: 2025-06-08 23:14:18.194534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54743fe68d3'
down_revision: Union[str, None] = '57b974ff7a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=11, scale=9),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed', 'quantity',
               existing_type=sa.Numeric(precision=11, scale=9),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
