"""add_feed_variance_and_alter_times

Revision ID: c5cc51a81409
Revises: 4156f1cb117f
Create Date: 2026-06-24 19:35:42.271044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cc51a81409'
down_revision: Union[str, None] = '4156f1cb117f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('composition_usage_history', 'times',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    op.add_column('financial_settings', sa.Column('default_feed_variance_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'financial_settings', 'chart_of_accounts', ['default_feed_variance_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_settings', type_='foreignkey')
    op.drop_column('financial_settings', 'default_feed_variance_account_id')
    op.alter_column('composition_usage_history', 'times',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
