"""Replace opening balance columns with virtual properties

Revision ID: d9e850d792ab
Revises: d7e78437a292
Create Date: 2025-08-12 08:05:19.875252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd9e850d792ab'
down_revision: Union[str, None] = 'd7e78437a292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_payments_id', table_name='payments')
    # op.drop_table('payments')
    op.drop_column('egg_room_reports', 'table_opening')
    op.drop_column('egg_room_reports', 'grade_c_opening')
    op.drop_column('egg_room_reports', 'jumbo_opening')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('jumbo_opening', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('egg_room_reports', sa.Column('grade_c_opening', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('egg_room_reports', sa.Column('table_opening', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # op.create_table('payments',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('purchase_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    # sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    # sa.Column('payment_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name='payments_purchase_order_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='payments_pkey')
    # )
    # op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
