"""immutable account_id

Revision ID: dcc721c95e0b
Revises: 935c7d48cf73
Create Date: 2026-02-21 07:35:50.614589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc721c95e0b'
down_revision: Union[str, None] = '935c7d48cf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_settings', sa.Column('is_initialized', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_constraint('operational_expenses_account_id_fkey', 'operational_expenses', type_='foreignkey')
    op.drop_column('operational_expenses', 'account_id')
    op.drop_constraint('payments_account_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'account_id')
    op.drop_constraint('sales_payments_account_id_fkey', 'sales_payments', type_='foreignkey')
    op.drop_column('sales_payments', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_payments', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sales_payments_account_id_fkey', 'sales_payments', 'chart_of_accounts', ['account_id'], ['id'])
    op.add_column('payments', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_account_id_fkey', 'payments', 'chart_of_accounts', ['account_id'], ['id'])
    op.add_column('operational_expenses', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('operational_expenses_account_id_fkey', 'operational_expenses', 'chart_of_accounts', ['account_id'], ['id'])
    op.drop_column('financial_settings', 'is_initialized')
    # ### end Alembic commands ###
