"""add_composite_pk_to_daily_batch

Revision ID: e9da5fb31ab6
Revises: c54743fe68d3
Create Date: 2025-11-19 12:23:56.934358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9da5fb31ab6'
down_revision: Union[str, None] = 'c54743fe68d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###