"""Add wastage_percentage to composition_usage_history

Revision ID: eab99fa03509
Revises: 2786d1eea53a
Create Date: 2026-06-03 08:00:26.201610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab99fa03509'
down_revision: Union[str, None] = '2786d1eea53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composition_usage_history', sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composition_usage_history', 'wastage_percentage')
    # ### end Alembic commands ###
