"""add wastage percentage in composition table

Revision ID: ef443c81c53b
Revises: e4e4e3517b54
Create Date: 2026-03-20 00:06:00.813280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef443c81c53b'
down_revision: Union[str, None] = 'e4e4e3517b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composition', sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composition', 'wastage_percentage')
    # ### end Alembic commands ###
