"""alter shed_no unique constraint on daily_batch table

Revision ID: f1bd2dd6af6d
Revises: 3965852a53de
Create Date: 2025-06-03 17:53:08.394702

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f1bd2dd6af6d'
down_revision: Union[str, None] = '3965852a53de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daily_batch_shed_no_key', 'daily_batch', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('daily_batch_shed_no_key', 'daily_batch', ['shed_no'])
    # ### end Alembic commands ###
