"""Added retained earnings and closed date

Revision ID: f5c6f13abcb3
Revises: 5547e4fc4de7
Create Date: 2026-05-21 20:38:11.931554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c6f13abcb3'
down_revision: Union[str, None] = '5547e4fc4de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_settings', sa.Column('retained_earnings_account_id', sa.Integer(), nullable=True))
    op.add_column('financial_settings', sa.Column('last_closed_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'financial_settings', 'chart_of_accounts', ['retained_earnings_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_settings', type_='foreignkey')
    op.drop_column('financial_settings', 'last_closed_date')
    op.drop_column('financial_settings', 'retained_earnings_account_id')
    # ### end Alembic commands ###
