"""empty message

Revision ID: f954e23fc3d7
Revises: fba431695248
Create Date: 2025-07-07 22:58:28.389641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f954e23fc3d7'
down_revision: Union[str, None] = 'fba431695248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('egg_room_reports')
    # op.drop_index('ix_feed_audit_id', table_name='feed_audit')
    # op.drop_table('feed_audit')
    # op.drop_index('ix_app_config_id', table_name='app_config')
    # op.drop_table('app_config')
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.drop_table('users')
    op.add_column('batch', sa.Column('closing_date', sa.Date(), nullable=True))
    # op.create_index(op.f('ix_bovanswhitelayerperformance_age_weeks'), 'bovanswhitelayerperformance', ['age_weeks'], unique=False)
    op.drop_column('daily_batch', 'standard_hen_day_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_batch', sa.Column('standard_hen_day_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # op.drop_index(op.f('ix_bovanswhitelayerperformance_age_weeks'), table_name='bovanswhitelayerperformance')
    op.drop_column('batch', 'closing_date')
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('is_superuser', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='users_pkey')
    # )
    # op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # op.create_table('app_config',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='app_config_pkey'),
    # sa.UniqueConstraint('name', name='app_config_name_key')
    # )
    # op.create_index('ix_app_config_id', 'app_config', ['id'], unique=False)
    # op.create_table('feed_audit',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('change_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('old_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('new_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('changed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name='feed_audit_feed_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='feed_audit_pkey')
    # )
    # op.create_index('ix_feed_audit_id', 'feed_audit', ['id'], unique=False)
    # op.create_table('egg_room_reports',
    # sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    # sa.Column('table_opening', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('table_received', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('table_transfer', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('table_damage', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('table_out', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('table_closing', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_opening', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_shed_received', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_room_received', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_transfer', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_labour', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_waste', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('grade_c_closing', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_opening', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_received', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_transfer', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_waste', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_in', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jumbo_closing', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('report_date', name='egg_room_reports_pkey')
    # )
    # ### end Alembic commands ###
