"""Replace virtual opening columns with actual opening columns

Revision ID: feb67b746cd4
Revises: d9e850d792ab
Create Date: 2025-08-12 17:49:28.680881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb67b746cd4'
down_revision: Union[str, None] = 'd9e850d792ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egg_room_reports', sa.Column('table_opening', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('jumbo_opening', sa.Integer(), nullable=True))
    op.add_column('egg_room_reports', sa.Column('grade_c_opening', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egg_room_reports', 'grade_c_opening')
    op.drop_column('egg_room_reports', 'jumbo_opening')
    op.drop_column('egg_room_reports', 'table_opening')
    # ### end Alembic commands ###
