"""redesign composition usage

Revision ID: g279a49782e4
Revises: f954e23fc3d7
Create Date: 2025-10-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import json


# revision identifiers, used by Alembic.
revision = 'g279a49782e4'
down_revision = 'f954e23fc3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    pass
